save hashed master password in  separate table

diff --git a/password-manager b/password-manager
--- a/password-manager
+++ b/password-manager
@@ -26,15 +26,36 @@ DEFAULT_DATABASE_NAME="passwords.db"
 FIRST_LOGIN=0
 
 setupDB() {
-	debug "called setup"
 	mkdir -p "$DEFAULT_DATABASE_LOCATION" 	|| fatal "Could not create '$DEFAULT_DATABASE_LOCATION'"  3
 	cd "$DEFAULT_DATABASE_LOCATION"		|| fatal "Could not move to '$DEFAULT_DATABASE_LOCATION'" 3
 	touch "$DEFAULT_DATABASE_NAME"		|| fatal "Could not create '$DEFAULT_DATABASE_NAME'"	  3
 	
 	sqlite3 "$DEFAULT_DATABASE_NAME" \
-		"CREATE TABLE passwords (id INTEGER PRIMARY KEY, account_name TEXT NOT NULL, password TEXT NOT NULL)"
+		"CREATE TABLE passwords (id INTEGER PRIMARY KEY, website TEXT NOT NULL, name TEXT NOT NULL, password TEXT NOT NULL)" \
+		"CREATE TABLE config (salt TEXT NOT NULL, master_hash TEXT NOT NULL)"
 
 	FIRST_LOGIN=1
+}
+
+newPassword() {
+	local website=$1
+	local name=$2
+	local password=$3
+
+	debug "creating new row with entries: $website, $name and $password"
+
+	sqlite3 "$DEFAULT_DATABASE_NAME" \
+		"INSERT INTO passwords (website, name, password) VALUES ('$website', '$name', '$password')"
+}
+
+saveUniversal() {
+	local password=$1
+	local salt=$(openssl rand -base64 16)
+	local crypted=$(argon2 $salt -id <<< $password | grep '^Hash:' | awk '{print $2}')
+
+	sqlite3 "$DEFAULT_DATABASE_NAME" \
+		"INSERT INTO config (salt, master_hash) VALUES ('$salt', '$crypted')" \
+		"SELECT * FROM config"
 }
 
 main() {
@@ -45,13 +66,29 @@ main() {
 	# if database does not exits, create it
 	ls "$DEFAULT_DATABASE_LOCATION/$DEFAULT_DATABASE_NAME" &> /dev/null || setupDB
 
-	local manager_pwd
+	local manager_pwd confirm_manager_pwd
 	if [[ $FIRST_LOGIN -eq 1 ]]; then
-		echo "First of all, let's create the password for this manager"
-		echo "It'll be the only password you'll have to remember, so make sure it's secure!"
-		echo
-		read -sp "Insert here your password: " manager_pwd
-		echo
+		while true; do
+			clear
+			echo "First of all, let's create the password for this manager"
+			echo "It'll be the only password you'll have to remember, so make sure it's secure!"
+			echo
+			read -rsp "Insert here your password: " manager_pwd
+			echo
+			read -rsp "Confirm your password: " confirm_manager_pwd
+			echo
+
+			if [[ $manager_pwd != $confirm_manager_pwd ]]; then
+				error "The passwords must coincide"
+				read -s -n 1
+				continue
+			fi
+			break
+		done
+
+		saveUniversal "$manager_pwd"
+	else
+		cd "$DEFAULT_DATABASE_LOCATION" || fatal "Could not move to $!"
 	fi
 
 	# show interface
