can now save passwords and delete database

diff --git a/password-manager b/password-manager
--- a/password-manager
+++ b/password-manager
@@ -9,6 +9,9 @@ info() {
 debug() {
 	echo "[debug] $1"
 }
+warning() {
+	echo "[attention] $1"
+}
 error() {
 	echo "[error] $1" >&2
 }
@@ -24,29 +27,105 @@ pressToContinue() {
 	read -r -n 1 -p "Press any key to continue..."
 }
 
+cleanup() {
+	unset MASTER_PASSWORD
+}
+trap cleanup EXIT
+
 DEFAULT_DATABASE_LOCATION="$HOME/.config/password_manager/"
 DEFAULT_DATABASE_NAME="passwords.db"
-FIRST_LOGIN=0
+MASTER_PASSWORD=
 
-setupDB() {
+firstLogin() {
 	mkdir -p "$DEFAULT_DATABASE_LOCATION" 	|| fatal "Could not create '$DEFAULT_DATABASE_LOCATION'"  3
 	cd "$DEFAULT_DATABASE_LOCATION"		|| fatal "Could not move to '$DEFAULT_DATABASE_LOCATION'" 3
 	touch "$DEFAULT_DATABASE_NAME"		|| fatal "Could not create '$DEFAULT_DATABASE_NAME'"	  3
 	
 	sqlite3 "$DEFAULT_DATABASE_NAME" \
-		"CREATE TABLE passwords (id INTEGER PRIMARY KEY, website TEXT NOT NULL, name TEXT NOT NULL, password TEXT NOT NULL)" \
-		"CREATE TABLE config (salt TEXT NOT NULL, master_hash TEXT NOT NULL)"
+		"CREATE TABLE passwords (id INTEGER PRIMARY KEY, website TEXT, name TEXT, ciphertext TEXT);" \
+		"CREATE TABLE config (salt TEXT NOT NULL, master_hash TEXT NOT NULL);"
 
-	FIRST_LOGIN=1
+	while true; do
+		clear
+		echo "First of all, let's create the password for this manager"
+		echo "It'll be the only password you'll have to remember, so make sure it's secure!"
+		echo
+		read -rsp "Insert here your password: " MASTER_PASSWORD
+		echo
+		read -rsp "Confirm your password: " confirm_master_pwd
+		echo
+
+		if [[ $MASTER_PASSWORD != "$confirm_master_pwd" ]]; then
+			error "The passwords must coincide"
+			pressToContinue
+			continue
+		fi
+		break
+	done
+
+	saveUniversal "$MASTER_PASSWORD"
+	echo
+	echo "Password saved succesfully!"
+	pressToContinue
 }
 
 newPassword() {
-	local website=$1
-	local name=$2
-	local password=$3
+	local website name password1 password2
 
+	while true; do
+		read -rp "Insert the website or service: " website
+		if [[ -z $website ]]; then
+			error "You must give a website or service!"
+			pressToContinue
+			echo -e  "\033[4A" # move cursor up 4 lines
+			echo -ne "\033[0J" # clear terminal below cursor and don't print \n
+			continue
+		fi
+		break
+	done
+	
+	while true; do
+		read -rp "Insert the username: " name
+		if [[ -z $name ]]; then
+			error "You must insert your username!"
+			pressToContinue
+			echo -ne "\033[3A\033[0J"
+			continue
+		fi
+		break
+	done
+
+	while true; do
+		read -rsp "Insert the password: " password1; echo
+		if [[ -z $password1 ]]; then
+			error "You must insert a password!"
+			pressToContinue
+			echo -ne "\033[3A\033[0J"
+			continue
+		fi
+
+		read -rsp "Confirm the password: " password2; echo
+		if [[ $password1 != "$password2" ]]; then
+			error "The passwords must coincide!"
+			pressToContinue
+			echo -ne "\033[4A\033[0J"
+			continue
+		fi
+		break
+	done
+
+	echo -n "Encrypting password... "
+	local ciphertext
+	ciphertext=$(echo "$password1" | gpg --batch -q --pinentry-mode loopback --passphrase-fd 3 -c \
+						--cipher-algo AES256 --s2k-mode 3 --s2k-digest-algo SHA512 \
+						--s2k-count 65011712 3<<< "$MASTER_PASSWORD" | base64 -w0)
+	
 	sqlite3 "$DEFAULT_DATABASE_NAME" \
-		"INSERT INTO passwords (website, name, password) VALUES ('$website', '$name', '$password')"
+		"INSERT INTO passwords (website, name, ciphertext) VALUES ('$website', '$name', '$ciphertext');"
+
+	sleep 1
+	echo "done"
+	sleep 1
 }
 
 saveUniversal() {
@@ -55,13 +134,13 @@ saveUniversal() {
 	local crypted 	; crypted=$(argon2 "$salt" -id <<< "$password" | grep '^Hash:' | awk '{print $2}')
 
 	sqlite3 "$DEFAULT_DATABASE_NAME" \
-		"INSERT INTO config (salt, master_hash) VALUES ('$salt', '$crypted')"
+		"INSERT INTO config (salt, master_hash) VALUES ('$salt', '$crypted');"
 }
 
 checkMasterPwd() {
 	local pwd_try=$1
-	local salt	; salt=$(sqlite3 "$DEFAULT_DATABASE_NAME" "SELECT salt FROM config")
-	local correct_pwd;correct_pwd=$(sqlite3 "$DEFAULT_DATABASE_NAME" "SELECT master_hash FROM config")
+	local salt	 ; salt=$(sqlite3 "$DEFAULT_DATABASE_NAME" "SELECT salt FROM config")
+	local correct_pwd; correct_pwd=$(sqlite3 "$DEFAULT_DATABASE_NAME" "SELECT master_hash FROM config")
 
 	pwd_try=$(argon2 "$salt" -id <<< "$pwd_try" | grep '^Hash:' | awk '{print $2}')
 
@@ -75,60 +154,64 @@ checkMasterPwd() {
 main() {
 	clear
 
-	sqlite3 --help &> /dev/null || fatal "'sqlite3' package is required but was not detected!" 2
+	sqlite3 --version &> /dev/null || fatal "'sqlite3' package is required but was not found!" 2
+	! argon2  -h 	  &> /dev/null || fatal "'argon2' package is required but was not found!"  2
+	openssl -v	  &> /dev/null || fatal "'openssl' package is required but was not found!" 2
+	gpg --version	  &> /dev/null || fatal "'gpg' package is required but was not found!" 	   2
 
-	ls "$DEFAULT_DATABASE_LOCATION/$DEFAULT_DATABASE_NAME" &> /dev/null || setupDB
+	ls "$DEFAULT_DATABASE_LOCATION/$DEFAULT_DATABASE_NAME" &> /dev/null ||firstLogin 
 
-	local manager_pwd confirm_manager_pwd
-	if [[ $FIRST_LOGIN -eq 1 ]]; then
-		while true; do
-			clear
-			echo "First of all, let's create the password for this manager"
-			echo "It'll be the only password you'll have to remember, so make sure it's secure!"
-			echo
-			read -rsp "Insert here your password: " manager_pwd
-			echo
-			read -rsp "Confirm your password: " confirm_manager_pwd
-			echo
+	cd "$DEFAULT_DATABASE_LOCATION" || fatal "Could not move to $!"
 
-			if [[ $manager_pwd != "$confirm_manager_pwd" ]]; then
-				error "The passwords must coincide"
-				pressToContinue
-				continue
-			fi
-			break
-		done
-
-		saveUniversal "$manager_pwd"
+	while true; do
+		clear
+		read -rsp "Insert your master password: " MASTER_PASSWORD
 		echo
-		echo "Password saved succesfully!"
-		pressToContinue
-	else
-		cd "$DEFAULT_DATABASE_LOCATION" || fatal "Could not move to $!"
 
-		local password_try
-		while true; do
-			clear
-			read -rsp "Insert your master password: " password_try
+		if checkMasterPwd "$MASTER_PASSWORD"; then
 			echo
-
-			if checkMasterPwd "$password_try"; then
-				echo
-				error "Invalid password, try again..."
-				pressToContinue
-				continue
-			fi
-			break
-		done
-		debug "correct password"
-	fi
+			error "Invalid password, try again..."
+			pressToContinue
+			continue
+		fi
+		break
+	done
+	debug "correct password"
 	
 	# show interface
-	clear
-	echo "WELCOME"
-	echo
+	local choice
+	while true; do
+		clear
+		echo "WELCOME"
+		echo
+		echo "What would you like to do?"
+		echo "[1] Add a new password"
+		echo "[2] Modify an existing password"
+		echo "[3] View a password"
+		echo "[4] View all entries (crypted)"
+		echo "[5] Clear the database (/!\\)"
+		echo "[0] Exit"
 
-	return 0
+		read -rp "> " choice
+		echo
+		
+		case $choice in
+			1) newPassword ; continue ;;
+			2) ;;
+			3) ;;
+			4) sqlite3 "$DEFAULT_DATABASE_NAME" "SELECT * FROM passwords" ; pressToContinue ; continue ;;
+			5)
+				warning "Are you sure? This will destroy all saved passwords, including the Master Password, forever (a very long time)!";
+				read -rp "Write 'Destroy my database' to confirm: " destruction;
+				if [[ $destruction == "Destroy my database" ]]; then
+					rm -r "$DEFAULT_DATABASE_LOCATION"
+				fi;
+				firstLogin;
+				continue;;
+			0) echo "See you later!" ; exit 0 ;;
+			*) error "Invalid option" ; pressToContinue ; continue ;;
+		esac
+	done
 }
 
 main "$@"
