setupDB and get universal password

diff --git a/password-manager b/password-manager
--- a/password-manager
+++ b/password-manager
@@ -21,14 +21,40 @@ fatal() {
 	fi
 }
 
-DEFAULT_DATABASE="$HOME/.config/password_manager/passwords.db"
+DEFAULT_DATABASE_LOCATION="$HOME/.config/password_manager/"
+DEFAULT_DATABASE_NAME="passwords.db"
+FIRST_LOGIN=0
+
+setupDB() {
+	debug "called setup"
+	mkdir -p "$DEFAULT_DATABASE_LOCATION" 	|| fatal "Could not create '$DEFAULT_DATABASE_LOCATION'"  3
+	cd "$DEFAULT_DATABASE_LOCATION"		|| fatal "Could not move to '$DEFAULT_DATABASE_LOCATION'" 3
+	touch "$DEFAULT_DATABASE_NAME"		|| fatal "Could not create '$DEFAULT_DATABASE_NAME'"	  3
+	
+	sqlite3 "$DEFAULT_DATABASE_NAME" \
+		"CREATE TABLE passwords (id INTEGER PRIMARY KEY, account_name TEXT NOT NULL, password TEXT NOT NULL)"
+
+	FIRST_LOGIN=1
+}
 
 main() {
+	clear
 	# check if sqlite is installed
 	sqlite3 --help &> /dev/null || fatal "'sqlite3' package is required but was not detected!" 2
 
+	# if database does not exits, create it
+	ls "$DEFAULT_DATABASE_LOCATION/$DEFAULT_DATABASE_NAME" &> /dev/null || setupDB
+
+	local manager_pwd
+	if [[ $FIRST_LOGIN -eq 1 ]]; then
+		echo "First of all, let's create the password for this manager"
+		echo "It'll be the only password you'll have to remember, so make sure it's secure!"
+		echo
+		read -sp "Insert here your password: " manager_pwd
+		echo
+	fi
+
 	# show interface
-	clear
 	echo "Password manager"
 
 	return 0
