Check for sqlite3

diff --git a/password-manager b/password-manager
--- a/password-manager
+++ b/password-manager
@@ -1,6 +1,6 @@
 #!/bin/env bash
 # Created by Carletti Stefano
-# date: dom 20 set 2026, 01:15:20, CEST
+# date: dom 20 set 2026, 23:15:20, CEST
 # MIT License
 
 info() {
@@ -21,7 +21,13 @@ fatal() {
 	fi
 }
 
+DEFAULT_DATABASE="$HOME/.config/password_manager/passwords.db"
+
 main() {
+	# check if sqlite is installed
+	sqlite3 --help &> /dev/null || fatal "'sqlite3' package is required but was not detected!" 2
+
+	# show interface
 	clear
 	echo "Password manager"
 
